#ifndef IncludeAll_H
#define IncludeAll_H

#include "../../src/accounting/Accounting.h"
#include "../../src/accounting/BillStrategy.h"
#include "../../src/accounting/Billing.h"
#include "../../src/accounting/CardBill.h"
#include "../../src/accounting/CashBill.h"
#include "../../src/accounting/CloseTab.h"
#include "../../src/accounting/Inventory.h"
#include "../../src/accounting/MultiBill.h"
#include "../../src/accounting/OpenTab.h"
#include "../../src/accounting/OverdueTab.h"
#include "../../src/accounting/Tab.h"
#include "../../src/accounting/TabState.h"

#include "../../src/cooking/Baker.h"
#include "../../src/cooking/Chef.h"
#include "../../src/cooking/Cook.h"
#include "../../src/cooking/Cuisine.h"
#include "../../src/cooking/DeputyHeadChef.h"
#include "../../src/cooking/Drink.h"
#include "../../src/cooking/FryChef.h"
#include "../../src/cooking/GrillChef.h"
#include "../../src/cooking/HeadChef.h"
#include "../../src/cooking/Kitchen.h"
#include "../../src/cooking/Meal.h"
#include "../../src/cooking/StationChef.h"

#include "../../src/customercare/Customer.h"
#include "../../src/customercare/CustomerNPC.h"
#include "../../src/customercare/CustomerTemplate.h"
#include "../../src/customercare/Happy.h"
#include "../../src/customercare/Neutral.h"
#include "../../src/customercare/SatisfactionState.h"
#include "../../src/customercare/Unhappy.h"
#include "../../src/customercare/VeryUnhappy.h"

#include "../../src/ordering/AbstractOrder.h"
#include "../../src/ordering/Beverage.h"
#include "../../src/ordering/Food.h"
#include "../../src/ordering/Menu.h"
#include "../../src/ordering/MenuItem.h"
#include "../../src/ordering/Order.h"
#include "../../src/ordering/OrderBuilder.h"
#include "../../src/ordering/Waiter.h"

#include "../../src/reservation/GeneralSection.h"
#include "../../src/reservation/GeneralTable.h"
#include "../../src/reservation/Host.h"
#include "../../src/reservation/PrivateSection.h"
#include "../../src/reservation/PrivateTable.h"
#include "../../src/reservation/Receptionist.h"
#include "../../src/reservation/Reservation.h"
#include "../../src/reservation/ReservationSystem.h"
#include "../../src/reservation/Section.h"
#include "../../src/reservation/Table.h"

#include "../../src/management/Engine.h"
#include "../../src/management/GameComponent.h"
#include "../../src/management/GameEngine.h"
#include "../../src/management/PlayerInteraction.h"
#include "../../src/management/GameRunner.h"

#endif
